// =====================================================
// REPORTING & INSIGHTS TYPES
// Sprint 29: AI-driven reporting and strategic insights
// =====================================================

// =====================================================
// ENUMS
// =====================================================

/**
 * Report types
 */
export enum ReportType {
  CAMPAIGN = 'CAMPAIGN',           // Campaign performance report
  STRATEGY = 'STRATEGY',           // Strategy effectiveness report
  PERFORMANCE = 'PERFORMANCE',     // Overall performance metrics
  INSIGHTS = 'INSIGHTS',           // Strategic insights and recommendations
  CUSTOM = 'CUSTOM',               // Custom report from template
}

/**
 * Report generation status
 */
export enum ReportStatus {
  PENDING = 'PENDING',           // Queued for generation
  GENERATING = 'GENERATING',     // Currently generating
  COMPLETE = 'COMPLETE',         // Successfully generated
  FAILED = 'FAILED',             // Generation failed
}

/**
 * Report section types
 */
export enum ReportSectionType {
  EXECUTIVE_SUMMARY = 'EXECUTIVE_SUMMARY',
  METRICS_OVERVIEW = 'METRICS_OVERVIEW',
  PERFORMANCE_ANALYSIS = 'PERFORMANCE_ANALYSIS',
  LEAD_SCORING = 'LEAD_SCORING',
  SENTIMENT_ANALYSIS = 'SENTIMENT_ANALYSIS',
  AGENT_EFFECTIVENESS = 'AGENT_EFFECTIVENESS',
  STRATEGIC_INSIGHTS = 'STRATEGIC_INSIGHTS',
  RECOMMENDATIONS = 'RECOMMENDATIONS',
  CHARTS_VISUALIZATIONS = 'CHARTS_VISUALIZATIONS',
  CUSTOM = 'CUSTOM',
}

// =====================================================
// CORE INTERFACES
// =====================================================

/**
 * Report Template
 * Reusable report configuration
 */
export interface ReportTemplate {
  id: string;
  organizationId: string;

  // Template metadata
  name: string;
  description?: string;
  reportType: ReportType;

  // Template configuration
  sections: ReportSectionConfig[];
  metricsConfig: MetricsConfig;

  // GPT configuration
  gptPromptTemplate?: string;
  includeRecommendations: boolean;
  includeStrategicInsights: boolean;

  // Template options
  isDefault: boolean;
  isActive: boolean;

  // Ownership
  createdBy?: string;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Generated Report
 * Completed or in-progress report
 */
export interface GeneratedReport {
  id: string;
  organizationId: string;

  // Report metadata
  reportType: ReportType;
  templateId?: string;

  // References
  campaignId?: string;
  strategyId?: string;

  // Report content
  title: string;
  status: ReportStatus;

  // GPT-generated content
  executiveSummary?: string;
  keyFindings?: string[];
  strategicRecommendations?: string[];
  performanceAnalysis?: string;
  agentEffectivenessSummary?: string;
  sentimentAnalysis?: string;

  // Structured metrics snapshot
  metricsSnapshot: MetricsSnapshot;

  // Report sections
  sections: ReportSection[];

  // Chart data
  charts: ChartConfig[];

  // Metadata
  generationStartedAt?: string;
  generationCompletedAt?: string;
  generationDurationMs?: number;

  // Error tracking
  errorMessage?: string;
  retryCount: number;

  // Timeframe
  periodStart?: string;
  periodEnd?: string;

  // Generated by
  requestedBy?: string;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Report Section
 * Individual section within a report
 */
export interface ReportSection {
  id?: string;
  type: ReportSectionType;
  title: string;
  content: string; // Markdown or HTML
  order: number;
  metadata?: Record<string, unknown>;
}

/**
 * Report Section Configuration
 * Template for report sections
 */
export interface ReportSectionConfig {
  type: ReportSectionType;
  title: string;
  enabled: boolean;
  order: number;
  gptPrompt?: string; // Custom GPT prompt for this section
}

/**
 * Metrics Configuration
 * Which metrics to include in report
 */
export interface MetricsConfig {
  includeContacts?: boolean;
  includeOutreach?: boolean;
  includeLeadScoring?: boolean;
  includeSentiment?: boolean;
  includeAgentPerformance?: boolean;
  includeTasks?: boolean;
  includeGoals?: boolean;
  includeTimeline?: boolean;
  customMetrics?: string[];
}

/**
 * Metrics Snapshot
 * Point-in-time metrics data
 */
export interface MetricsSnapshot {
  period: {
    start: string;
    end: string;
  };
  contacts?: ContactMetrics;
  outreach?: OutreachMetrics;
  leadScoring?: LeadScoringMetrics;
  sentiment?: SentimentMetrics;
  agents?: AgentMetrics;
  tasks?: TaskMetrics;
  goals?: GoalMetrics;
  custom?: Record<string, unknown>;
}

/**
 * Contact Metrics
 */
export interface ContactMetrics {
  total: number;
  qualified: number;
  disqualified: number;
  newThisPeriod: number;
  conversionRate?: number;
}

/**
 * Outreach Metrics
 */
export interface OutreachMetrics {
  pitches: number;
  placements: number;
  replies: number;
  opens: number;
  conversionRate: number;
  replyRate?: number;
  openRate?: number;
}

/**
 * Lead Scoring Metrics
 */
export interface LeadScoringMetrics {
  avgScore: number;
  qualifiedCount: number;
  disqualifiedCount: number;
  greenCount: number;
  amberCount: number;
  redCount: number;
  qualificationRate: number;
}

/**
 * Sentiment Metrics
 */
export interface SentimentMetrics {
  avgScore: number;
  positiveCount: number;
  neutralCount: number;
  negativeCount: number;
  trendDirection: 'IMPROVING' | 'DECLINING' | 'STABLE';
}

/**
 * Agent Metrics
 */
export interface AgentMetrics {
  totalRuns: number;
  successfulRuns: number;
  failedRuns: number;
  avgExecutionTime: number;
  successRate: number;
}

/**
 * Task Metrics
 */
export interface TaskMetrics {
  total: number;
  completed: number;
  pending: number;
  failed: number;
  completionRate: number;
  avgCompletionTime?: number;
}

/**
 * Reporting Goal Metrics
 */
export interface ReportingGoalMetrics {
  total: number;
  achieved: number;
  inProgress: number;
  achievementRate: number;
}

/**
 * Chart Configuration
 * Chart data for visualization
 */
export interface ChartConfig {
  id: string;
  type: 'line' | 'bar' | 'pie' | 'doughnut' | 'radar' | 'area';
  title: string;
  data: ChartData;
  options?: Record<string, unknown>;
}

/**
 * Chart Data
 */
export interface ChartData {
  labels: string[];
  datasets: ChartDataset[];
}

/**
 * Chart Dataset
 */
export interface ChartDataset {
  label: string;
  data: number[];
  backgroundColor?: string | string[];
  borderColor?: string | string[];
  fill?: boolean;
  [key: string]: unknown;
}

// =====================================================
// SUMMARIES & INSIGHTS
// =====================================================

/**
 * Performance Summary
 * High-level performance analysis
 */
export interface PerformanceSummary {
  campaignId?: string;
  periodStart: string;
  periodEnd: string;

  // Overall metrics
  overallScore: number; // 0-100
  trend: 'IMPROVING' | 'DECLINING' | 'STABLE';

  // GPT-generated insights
  summaryText: string;
  highlights: string[];
  concerns: string[];

  // Category breakdowns
  contactPerformance: number; // 0-100
  outreachPerformance: number; // 0-100
  leadQualityPerformance: number; // 0-100
  sentimentPerformance: number; // 0-100
}

/**
 * Agent Effectiveness Summary
 * Analysis of agent performance
 */
export interface AgentEffectivenessSummary {
  campaignId?: string;
  periodStart: string;
  periodEnd: string;

  // Agent metrics
  totalAgents: number;
  activeAgents: number;
  totalRuns: number;
  successRate: number;

  // GPT analysis
  effectivenessScore: number; // 0-100
  summaryText: string;
  topPerformingAgents: AgentPerformance[];
  underperformingAgents: AgentPerformance[];
  recommendations: string[];
}

/**
 * Agent Performance
 */
export interface AgentPerformance {
  agentId: string;
  agentName: string;
  runs: number;
  successRate: number;
  avgExecutionTime: number;
  score: number; // 0-100
  insights?: string;
}

/**
 * Strategic Insight
 * GPT-generated strategic recommendation
 */
export interface StrategicInsight {
  id: string;
  category: 'OPPORTUNITY' | 'RISK' | 'OPTIMIZATION' | 'STRATEGIC';
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  title: string;
  description: string;
  dataPoints: string[]; // Supporting evidence
  recommendations: string[];
  estimatedImpact?: 'HIGH' | 'MEDIUM' | 'LOW';
}

/**
 * Sentiment Trend Analysis
 * GPT analysis of sentiment over time
 */
export interface SentimentTrendAnalysis {
  periodStart: string;
  periodEnd: string;

  // Metrics
  avgSentiment: number; // 0-100
  trendDirection: 'IMPROVING' | 'DECLINING' | 'STABLE';
  volatility: 'HIGH' | 'MEDIUM' | 'LOW';

  // GPT insights
  summaryText: string;
  keyDrivers: string[];
  concerningPatterns?: string[];
  positivePatterns?: string[];
  recommendations: string[];
}

/**
 * Lead Funnel Analysis
 * GPT analysis of lead qualification pipeline
 */
export interface LeadFunnelAnalysis {
  periodStart: string;
  periodEnd: string;

  // Funnel metrics
  totalLeads: number;
  qualifiedLeads: number;
  disqualifiedLeads: number;
  conversionRate: number;

  // Stage breakdown
  stageDistribution: {
    unqualified: number;
    inProgress: number;
    qualified: number;
    disqualified: number;
  };

  // GPT insights
  summaryText: string;
  bottlenecks: string[];
  opportunities: string[];
  recommendations: string[];
}

// =====================================================
// INPUT TYPES
// =====================================================

/**
 * Generate Report Input
 */
export interface GenerateReportInput {
  campaignId?: string;
  strategyId?: string;
  organizationId: string;
  reportType: ReportType;
  templateId?: string;
  periodStart?: string;
  periodEnd?: string;
  requestedBy?: string;
}

/**
 * Create Report Template Input
 */
export interface CreateReportTemplateInput {
  organizationId: string;
  name: string;
  description?: string;
  reportType: ReportType;
  sections: ReportSectionConfig[];
  metricsConfig: MetricsConfig;
  gptPromptTemplate?: string;
  includeRecommendations?: boolean;
  includeStrategicInsights?: boolean;
  isDefault?: boolean;
  createdBy?: string;
}

/**
 * Update Report Template Input
 */
export interface UpdateReportTemplateInput {
  templateId: string;
  name?: string;
  description?: string;
  sections?: ReportSectionConfig[];
  metricsConfig?: MetricsConfig;
  gptPromptTemplate?: string;
  includeRecommendations?: boolean;
  includeStrategicInsights?: boolean;
  isActive?: boolean;
}

/**
 * Retry Report Input
 */
export interface RetryReportInput {
  reportId: string;
  organizationId: string;
}

/**
 * Generate Summary Input
 */
export interface GenerateSummaryInput {
  campaignId: string;
  organizationId: string;
  periodStart?: string;
  periodEnd?: string;
  includeRecommendations?: boolean;
}

// =====================================================
// OUTPUT TYPES
// =====================================================

/**
 * Report List Result
 */
export interface ReportListResult {
  reports: GeneratedReport[];
  total: number;
}

/**
 * Template List Result
 */
export interface TemplateListResult {
  templates: ReportTemplate[];
  total: number;
}

/**
 * Report Sections Result
 */
export interface ReportSectionsResult {
  sections: ReportSection[];
  total: number;
}

// =====================================================
// RESPONSE TYPES
// =====================================================

/**
 * Generate Report Response
 */
export interface GenerateReportResponse {
  success: boolean;
  reportId?: string;
  status?: ReportStatus;
  error?: string;
}

/**
 * Get Report Response
 */
export interface GetReportResponse {
  success: boolean;
  report?: GeneratedReport;
  error?: string;
}

/**
 * Get Reports Response
 */
export interface GetReportsResponse {
  success: boolean;
  reports?: GeneratedReport[];
  total?: number;
  error?: string;
}

/**
 * Get Template Response
 */
export interface GetTemplateResponse {
  success: boolean;
  template?: ReportTemplate;
  error?: string;
}

/**
 * Get Templates Response
 */
export interface GetTemplatesResponse {
  success: boolean;
  templates?: ReportTemplate[];
  total?: number;
  error?: string;
}

/**
 * Generate Summary Response
 */
export interface GenerateSummaryResponse {
  success: boolean;
  summary?: PerformanceSummary;
  error?: string;
}

/**
 * Get Sections Response
 */
export interface GetSectionsResponse {
  success: boolean;
  sections?: ReportSection[];
  total?: number;
  error?: string;
}

// =====================================================
// UTILITY TYPES
// =====================================================

/**
 * Report Type Configuration
 */
export interface ReportTypeConfig {
  type: ReportType;
  label: string;
  description: string;
  icon: string;
  color: string;
}

/**
 * Report Status Configuration
 */
export interface ReportStatusConfig {
  status: ReportStatus;
  label: string;
  color: string;
  icon: string;
}

/**
 * Report Section Type Configuration
 */
export interface ReportSectionTypeConfig {
  type: ReportSectionType;
  label: string;
  description: string;
  icon: string;
}

// =====================================================
// CONSTANTS
// =====================================================

export const REPORT_TYPE_CONFIGS: Record<ReportType, ReportTypeConfig> = {
  [ReportType.CAMPAIGN]: {
    type: ReportType.CAMPAIGN,
    label: 'Campaign Report',
    description: 'Comprehensive campaign performance analysis',
    icon: 'target',
    color: '#3B82F6', // blue-500
  },
  [ReportType.STRATEGY]: {
    type: ReportType.STRATEGY,
    label: 'Strategy Report',
    description: 'Strategic effectiveness and ROI analysis',
    icon: 'trending-up',
    color: '#10B981', // green-500
  },
  [ReportType.PERFORMANCE]: {
    type: ReportType.PERFORMANCE,
    label: 'Performance Report',
    description: 'Overall platform and agent performance',
    icon: 'activity',
    color: '#8B5CF6', // purple-500
  },
  [ReportType.INSIGHTS]: {
    type: ReportType.INSIGHTS,
    label: 'Insights Report',
    description: 'Strategic insights and recommendations',
    icon: 'lightbulb',
    color: '#F59E0B', // amber-500
  },
  [ReportType.CUSTOM]: {
    type: ReportType.CUSTOM,
    label: 'Custom Report',
    description: 'Customized report from template',
    icon: 'file-text',
    color: '#6B7280', // gray-500
  },
};

export const REPORT_STATUS_CONFIGS: Record<ReportStatus, ReportStatusConfig> = {
  [ReportStatus.PENDING]: {
    status: ReportStatus.PENDING,
    label: 'Pending',
    color: '#6B7280', // gray-500
    icon: 'clock',
  },
  [ReportStatus.GENERATING]: {
    status: ReportStatus.GENERATING,
    label: 'Generating',
    color: '#3B82F6', // blue-500
    icon: 'loader',
  },
  [ReportStatus.COMPLETE]: {
    status: ReportStatus.COMPLETE,
    label: 'Complete',
    color: '#10B981', // green-500
    icon: 'check-circle',
  },
  [ReportStatus.FAILED]: {
    status: ReportStatus.FAILED,
    label: 'Failed',
    color: '#EF4444', // red-500
    icon: 'x-circle',
  },
};

export const REPORT_SECTION_TYPE_CONFIGS: Record<ReportSectionType, ReportSectionTypeConfig> = {
  [ReportSectionType.EXECUTIVE_SUMMARY]: {
    type: ReportSectionType.EXECUTIVE_SUMMARY,
    label: 'Executive Summary',
    description: 'High-level overview and key takeaways',
    icon: 'file-text',
  },
  [ReportSectionType.METRICS_OVERVIEW]: {
    type: ReportSectionType.METRICS_OVERVIEW,
    label: 'Metrics Overview',
    description: 'Key performance indicators',
    icon: 'bar-chart-2',
  },
  [ReportSectionType.PERFORMANCE_ANALYSIS]: {
    type: ReportSectionType.PERFORMANCE_ANALYSIS,
    label: 'Performance Analysis',
    description: 'Detailed performance breakdown',
    icon: 'trending-up',
  },
  [ReportSectionType.LEAD_SCORING]: {
    type: ReportSectionType.LEAD_SCORING,
    label: 'Lead Scoring Analysis',
    description: 'Lead quality and pipeline insights',
    icon: 'users',
  },
  [ReportSectionType.SENTIMENT_ANALYSIS]: {
    type: ReportSectionType.SENTIMENT_ANALYSIS,
    label: 'Sentiment Analysis',
    description: 'Contact sentiment trends and patterns',
    icon: 'heart',
  },
  [ReportSectionType.AGENT_EFFECTIVENESS]: {
    type: ReportSectionType.AGENT_EFFECTIVENESS,
    label: 'Agent Effectiveness',
    description: 'AI agent performance and efficiency',
    icon: 'cpu',
  },
  [ReportSectionType.STRATEGIC_INSIGHTS]: {
    type: ReportSectionType.STRATEGIC_INSIGHTS,
    label: 'Strategic Insights',
    description: 'AI-generated strategic recommendations',
    icon: 'lightbulb',
  },
  [ReportSectionType.RECOMMENDATIONS]: {
    type: ReportSectionType.RECOMMENDATIONS,
    label: 'Recommendations',
    description: 'Actionable next steps',
    icon: 'check-square',
  },
  [ReportSectionType.CHARTS_VISUALIZATIONS]: {
    type: ReportSectionType.CHARTS_VISUALIZATIONS,
    label: 'Charts & Visualizations',
    description: 'Visual data representations',
    icon: 'pie-chart',
  },
  [ReportSectionType.CUSTOM]: {
    type: ReportSectionType.CUSTOM,
    label: 'Custom Section',
    description: 'User-defined section',
    icon: 'edit',
  },
};

/**
 * Default report sections for campaign report
 */
export const DEFAULT_CAMPAIGN_SECTIONS: ReportSectionConfig[] = [
  {
    type: ReportSectionType.EXECUTIVE_SUMMARY,
    title: 'Executive Summary',
    enabled: true,
    order: 1,
  },
  {
    type: ReportSectionType.METRICS_OVERVIEW,
    title: 'Key Metrics',
    enabled: true,
    order: 2,
  },
  {
    type: ReportSectionType.PERFORMANCE_ANALYSIS,
    title: 'Performance Analysis',
    enabled: true,
    order: 3,
  },
  {
    type: ReportSectionType.LEAD_SCORING,
    title: 'Lead Quality & Pipeline',
    enabled: true,
    order: 4,
  },
  {
    type: ReportSectionType.SENTIMENT_ANALYSIS,
    title: 'Sentiment Analysis',
    enabled: true,
    order: 5,
  },
  {
    type: ReportSectionType.AGENT_EFFECTIVENESS,
    title: 'Agent Performance',
    enabled: true,
    order: 6,
  },
  {
    type: ReportSectionType.STRATEGIC_INSIGHTS,
    title: 'Strategic Insights',
    enabled: true,
    order: 7,
  },
  {
    type: ReportSectionType.RECOMMENDATIONS,
    title: 'Recommendations',
    enabled: true,
    order: 8,
  },
];

/**
 * Default metrics configuration
 */
export const DEFAULT_METRICS_CONFIG: MetricsConfig = {
  includeContacts: true,
  includeOutreach: true,
  includeLeadScoring: true,
  includeSentiment: true,
  includeAgentPerformance: true,
  includeTasks: true,
  includeGoals: true,
  includeTimeline: false,
  customMetrics: [],
};
