import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import campaignRoutes from './campaign.routes';
import contentRoutes from './content.routes';
import agentRoutes from './agent.routes';
import onboardingRoutes from './onboarding.routes';
import contactRoutes from './contact.routes';
import prCampaignRoutes from './pr-campaign.routes';
import agentTemplateRoutes from './agent-template.routes';
import pitchWorkflowRoutes from './pitch-workflow.routes';
import dashboardRoutes from './dashboard.routes';
import crmRoutes from './crm.routes';
import reputationRoutes from './reputation.routes';
import agentMemoryRoutes from './agent-memory.routes';
import agentMemoryLifecycleRoutes from './agent-memory-lifecycle.routes';
import agentPlanningRoutes from './agent-planning.routes';
import agentCollabRoutes from './agent-collab.routes';
import autonomousCampaignRoutes from './autonomous-campaign.routes';
import targetingRoutes from './targeting.routes';
import executionRoutes from './execution.routes';
import memoryRoutes from './memory.routes';
import knowledgeGraphRoutes from './knowledge-graph.routes';
import followupRoutes from './followup.routes';
import timelineRoutes from './timeline.routes';
import collaborationRoutes from './collaboration.routes';
import goalsRoutes from './goals.routes';
import channelIntelRoutes from './channel-intel.routes';
import leadScoringRoutes from './lead-scoring.routes';
import reportingRoutes from './reporting.routes';
import promptsRoutes from './prompts.routes';
import personaRoutes from './persona.routes';
import teamAnalyticsRoutes from './team-analytics.routes';
import competitiveIntelRoutes from './competitive-intel.routes';
import goalTrackingRoutes from './goal-tracking.routes';
import agentEvaluatorRoutes from './agent-evaluator.routes';
import promptTemplateRoutes from './prompt-template.routes';
import agentInteractionRoutes from './agent-interaction';
import agentAnalyticsRoutes from './agent-analytics';
import agentFeedbackRoutes from './agent-feedback';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/content', contentRoutes);
router.use('/agents', agentRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/contacts', contactRoutes);
router.use('/pr', prCampaignRoutes);
router.use('/agent-templates', agentTemplateRoutes);
router.use('/pitch-workflows', pitchWorkflowRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/crm', crmRoutes);
router.use('/reputation', reputationRoutes);
router.use('/agent-memory', agentMemoryRoutes);
router.use('/agent-memory-lifecycle', agentMemoryLifecycleRoutes);
router.use('/agent-planning', agentPlanningRoutes);
router.use('/agent-collab', agentCollabRoutes);
router.use('/autonomous', autonomousCampaignRoutes);
router.use('/targeting', targetingRoutes);
router.use('/execution', executionRoutes);
router.use('/memory', memoryRoutes);
router.use('/knowledge-graph', knowledgeGraphRoutes);
router.use('/followup', followupRoutes);
router.use('/timeline', timelineRoutes);
router.use('/collaboration', collaborationRoutes);
router.use('/goals', goalsRoutes);
router.use('/channel-intel', channelIntelRoutes);
router.use('/lead-scoring', leadScoringRoutes);
router.use('/reporting', reportingRoutes);
router.use('/prompts', promptsRoutes);
router.use('/personas', personaRoutes);
router.use('/team-analytics', teamAnalyticsRoutes);
router.use('/competitive-intel', competitiveIntelRoutes);
router.use('/goal-tracking', goalTrackingRoutes);
router.use('/agent-evaluator', agentEvaluatorRoutes);
router.use('/prompt-templates', promptTemplateRoutes);
router.use('/agent-interaction', agentInteractionRoutes);
router.use('/agent-analytics', agentAnalyticsRoutes);
router.use('/agent-feedback', agentFeedbackRoutes);

export default router;
